// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs10sVgw27SikkpGfZPM5sWzL15oh08q4',
    appId: '1:835800357564:web:b3d36cd071915bc6a48eb9',
    messagingSenderId: '835800357564',
    projectId: 'shop-app-7658c',
    authDomain: 'shop-app-7658c.firebaseapp.com',
    storageBucket: 'shop-app-7658c.appspot.com',
    measurementId: 'G-F7CS2FBF1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMi1YfFSnnzr6hfrOx3ARaiDgcBWFBBtU',
    appId: '1:835800357564:android:039cab33bed8b852a48eb9',
    messagingSenderId: '835800357564',
    projectId: 'shop-app-7658c',
    storageBucket: 'shop-app-7658c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwr3TcOZibTsUhMrEpGzjdAPXUdLKPEAo',
    appId: '1:835800357564:ios:df1ed24ba3016cc9a48eb9',
    messagingSenderId: '835800357564',
    projectId: 'shop-app-7658c',
    storageBucket: 'shop-app-7658c.appspot.com',
    iosClientId: '835800357564-7apa5i4s674l4r8q74b73tkm4ocsd0sc.apps.googleusercontent.com',
    iosBundleId: 'com.akshya.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwr3TcOZibTsUhMrEpGzjdAPXUdLKPEAo',
    appId: '1:835800357564:ios:df1ed24ba3016cc9a48eb9',
    messagingSenderId: '835800357564',
    projectId: 'shop-app-7658c',
    storageBucket: 'shop-app-7658c.appspot.com',
    iosClientId: '835800357564-7apa5i4s674l4r8q74b73tkm4ocsd0sc.apps.googleusercontent.com',
    iosBundleId: 'com.akshya.shopApp',
  );
}
